// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/reddit_api/client.dart';
import '../third_party/reddit_api/model/comment.dart';
import '../third_party/reddit_api/model/post.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void debugPost({required Post post}) =>
    RustLib.instance.api.crateApiRedditApiDebugPost(post: post);

void debugComment({required Comment comment}) =>
    RustLib.instance.api.crateApiRedditApiDebugComment(comment: comment);

class RedditAPI {
  const RedditAPI();

  static Client client() =>
      RustLib.instance.api.crateApiRedditApiRedditApiClient();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedditAPI && runtimeType == other.runtimeType;
}
