targets:
  $default:
    builders:
      crabir|settings_page:
        generate_for:
          - lib/**.dart
      crabir|go_router_ext:
        generate_for:
          - lib/**.dart

builders:
  settings_page:
    import: "package:crabir/src/settings_page/settings_page_generator.dart"
    builder_factories: ["settingsPageBuilder"]
    build_extensions: {".dart": [".settings_page.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  go_router_ext:
    import: "package:crabir/src/go_router_ext/go_router_ext_generator.dart"
    builder_factories: ["crabirRouteBuilder"]
    build_extensions: {".dart": [".go_route_ext.dart"]}
    auto_apply: dependents
    build_to: source

