[package]
name = "flutter_getter"
version = "0.1.0"
edition = "2024"
authors = ["Antoine Grimod"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "2"
proc-macro2 = { version = "1", default-features = false }
proc-macro-error2 = "2"
