[package]
name = "licenses_packer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.225", features = ["serde_derive"] }
serde_json = "1.0.145"
subprocess = "0.2.9"
